import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-pt">
      <head>
        <meta
          name="google-site-verification"
          content="knEDOpABC_nhwNpTOXYtQ_-STwz4nk0-uSWUWHyYLC8"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
